# Generated by Django 3.0.3 on 2020-02-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'verbose_name_plural': 'Snippet'},
        ),
        migrations.AddField(
            model_name='snippet',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
