# Generated by Django 3.0.3 on 2020-02-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20200206_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('date_time', models.DateTimeField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Snippet',
                'db_table': 'snippethistory',
            },
        ),
        migrations.AlterModelTable(
            name='snippet',
            table='snippet',
        ),
    ]
