# Generated by Django 3.0.3 on 2020-02-07 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20200207_1503'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='snippethistory',
            table='snippet_history',
        ),
    ]
